#!/usr/bin/env python2

import sys
import os
import os.path
import stat
import errno
import subprocess
from common import *

NPROCS = 4

def remove_nobakcontent_meta_dir(histdir, root):
    try:
        mfn = os.path.join(histdir, root)
        shutil.rmtree(mfn, ignore_errors=True)
    except EnvironmentError, e:
        if e.errno == errno.ENOENT:
            pass  # Skip.
        else:
            raise e

def remove_extra_meta_files(histdir, root, files, dirs):
    try:
        hist_entries = set(os.listdir(os.path.join(histdir, root)))
    except EnvironmentError, e:
        if e.errno in [errno.ENOENT, errno.ENOTDIR]:
            return
        else:
            raise e

    hist_entries.difference_update(files)
    hist_entries.difference_update(dirs)

    for m in hist_entries:
        try:
            mfn = os.path.join(histdir, root, m)
            if m == '.git' and os.path.normpath(root) == '.':
                continue

            st = os.lstat(mfn)
            if stat.S_ISDIR(st.st_mode):
                shutil.rmtree(mfn, ignore_errors=True)
            else:
                os.unlink(mfn)
        except EnvironmentError, e:
            if e.errno == errno.ENOENT:
                pass  # Skip disappeared.
            else:
                raise e

def queue_files(q, procs, current, root, files):
    for f in files:
        if root is not None:
            f = os.path.join(root, f)
        q.append(f)

        if len(q) >= 16:
            pr = procs[current]
            current = (current + 1) % len(procs)

            pr.stdin.write('\n'.join(q) + '\n')
            q = []
    return q, current

def isolate_directories(root, mixed_set):
    dirs = set()
    for f in mixed_set:
        if root is not None:
            f = os.path.join(root, f)
        if os.path.isdir(f):
            mixed_set.remove(f)
            dirs.add(f)
    return mixed_set, dirs

def find_all_files(d):
    r = []
    for root, _, files in os.walk(d):
        for f in files:
            r.append(os.path.join(root, f))
    return r

def main() :
    if len(sys.argv) < 3:
        eprint("Usage: %s <.bakcontent> <cmd> [args...]" % sys.argv[0])
        exit(1)

    bakdir = sys.argv[1]
    cmd = sys.argv[2]
    further_args = sys.argv[3:]

    if not os.path.isabs(bakdir):
        eprint("'%s' must be an absolute path" % bakdir)
        exit(1)
    if not os.path.isdir(bakdir):
        eprint("'%s' must be a directory" % bakdir)
        exit(1)

    # Drop priviledges to minimum.
    st = os.stat(bakdir)
    os.setgid(st.st_gid)
    os.setuid(st.st_uid)

    rootdir = get_rootdir(bakdir)
    histdir = os.path.join(bakdir, 'history')

    if cmd == 'snapshot':
        with pushdir(histdir):
            e = shell("git rm -rf --cached --ignore-unmatch * > /dev/null")
            if e:
                exit(e)

    # Make sure the subprocesses run in 'rootdir'
    with pushdir(rootdir):
        procs = [subprocess.Popen(
            "bakcontent-do-files %d %s %s %s" % (worker_id, bakdir, cmd, ' '.join(further_args)), \
                    close_fds=True, shell=True, stdin=subprocess.PIPE, bufsize=8192) \
                    for worker_id in range(NPROCS)]
        current = 1 % len(procs)  # worker 0 may have something special to do first.

    for pr in procs:
        e = pr.poll()
        if e:
            eprint("subprocess bakcontent-do-files failed with '%s'" % e)
            exit(e)

    with pushdir(rootdir):
        fns = []
        for root, dirs, files in os.walk('.'):
            if os.path.exists(os.path.join(root, '.nobakcontent')):
                del dirs[:]
                if cmd == 'snapshot':
                    remove_nobakcontent_meta_dir(histdir, root)
                continue
            try:
                dirs.remove('.bakcontent')
            except ValueError:
                pass

            fns, current = queue_files(fns, procs, current, root, files)

            if cmd == 'diff':
                only_hfiles = set(os.listdir(os.path.join(histdir, root)))
                only_hfiles -= set(files)
                if root == '.':
                    only_hfiles.discard('.git')
                only_hfiles, only_hdir = isolate_directories(root, only_hfiles)
                fns, current = queue_files(fns, procs, current, root, only_hfiles)
                for d in only_hdir:
                    fns, current = queue_files(fns, procs, current, None,
                            find_all_files(os.path.join(root, d)))

            elif cmd == 'snapshot':
                remove_extra_meta_files(histdir, root, files, dirs)

    if len(fns) > 0:
        pr = procs[current]
        pr.stdin.write('\n'.join(fns) + '\n')

    for pr in procs:
        pr.stdin.close()

    for pr in procs:
        e = pr.wait()
        if e:
            eprint("subprocess bakcontent-do-files failed with '%s'" % e)
            exit(e)

    if cmd == 'snapshot':
        with pushdir(histdir):
            e = shell("git add -A . > /dev/null")
            if e:
                eprint("Error in git add")
                exit(e)

            # Returns 1 if there is nothing to commit.
            ignore = shell("git commit -m. > /dev/null")

            e = shell("git clean -fd > /dev/null")
            if e:
                eprint("Error in git clean")
                exit(e)

            e = shell("git gc &> /dev/null")
            if e:
                eprint("Error in git gc")
                exit(e)

    elif cmd == 'store-sync':
        pass
    elif cmd == 'diff':
        pass
    else:
        eprint("Error: invalid command '%s'" % cmd)
        exit(1)

if __name__ == '__main__':
    try:
        main()
    except Exception, e:
        eprint(str(e))
        exit(1)
